name: pf_ui
description: Pink Fleets shared luxury UI design system – tokens, theme, and reusable components.
publish_to: none

version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cloud_firestore: ^5.4.4

flutter:
  uses-material-design: true
