// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88mPsi4HXs-vR3I0HBY2mljgrWmRc0a4',
    appId: '1:93607564611:web:9deb249bff8d2d409e4bf6',
    messagingSenderId: '93607564611',
    projectId: 'pink-fleets',
    authDomain: 'pink-fleets.firebaseapp.com',
    storageBucket: 'pink-fleets.firebasestorage.app',
    measurementId: 'G-WG0HDX0ZQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-VotzMnnMnTEa5Q4Y8R8glcSBoc96TY',
    appId: '1:93607564611:android:f9b961373d5137d09e4bf6',
    messagingSenderId: '93607564611',
    projectId: 'pink-fleets',
    storageBucket: 'pink-fleets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1CIcgYrmFQjdUI3MPcPhyH2i4Hx5y3A',
    appId: '1:93607564611:ios:60323321f7e87b469e4bf6',
    messagingSenderId: '93607564611',
    projectId: 'pink-fleets',
    storageBucket: 'pink-fleets.firebasestorage.app',
    iosBundleId: 'com.example.adminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU1CIcgYrmFQjdUI3MPcPhyH2i4Hx5y3A',
    appId: '1:93607564611:ios:60323321f7e87b469e4bf6',
    messagingSenderId: '93607564611',
    projectId: 'pink-fleets',
    storageBucket: 'pink-fleets.firebasestorage.app',
    iosBundleId: 'com.example.adminWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB88mPsi4HXs-vR3I0HBY2mljgrWmRc0a4',
    appId: '1:93607564611:web:fef61a8aed7721b09e4bf6',
    messagingSenderId: '93607564611',
    projectId: 'pink-fleets',
    authDomain: 'pink-fleets.firebaseapp.com',
    storageBucket: 'pink-fleets.firebasestorage.app',
    measurementId: 'G-S8064BD754',
  );
}
